POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "carlos",
    "password": "123"
}

###
POST  http://localhost:3000/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiY2FybG9zIiwicm9sZSI6ImFkaW0iLCJpYXQiOjE2NjUxNzI5MjEsImV4cCI6MTY2NTE3Mjk4MX0.1_VfTF92CuG6Ve9IjEY2d9dugL-ff_PZummDFHMWbrU


###
POST http://localhost:3000/cadastro
Content-Type: application/json

{
    "id":1,
    "username": "carlos",
    "password": "123",
    "role": "adim"
}